import type { Category, MenuItem } from './types'

export const CATEGORIES: { key: Category; label: string; emoji: string }[] = [
  { key: 'Breads', label: 'Breads', emoji: '🍞' },
  { key: 'Cakes', label: 'Cakes', emoji: '🎂' },
  { key: 'Pastries', label: 'Pastries', emoji: '🥐' },
  { key: 'Burgers', label: 'Burgers', emoji: '🍔' },
  { key: 'Pizza', label: 'Pizza', emoji: '🍕' },
  { key: 'Snacks', label: 'Snacks', emoji: '🍟' },
  { key: 'Beverages', label: 'Beverages', emoji: '🥤' },
]

const img = (id: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=800&q=70`

export const MENU: MenuItem[] = [
  // ---------------- Breads ----------------
  {
    id: 'sourdough',
    name: 'Artisan Sourdough',
    description: 'Slow-fermented crusty loaf with a soft, airy crumb.',
    price: 120,
    category: 'Breads',
    image: img('photo-1585478259715-876acc5be8eb'),
    badge: 'Bestseller',
    rating: 4.9,
  },
  {
    id: 'garlic-bread',
    name: 'Cheesy Garlic Bread',
    description: 'Toasted baguette loaded with garlic butter & mozzarella.',
    price: 90,
    category: 'Breads',
    image: img('photo-1573140247632-f8fd74997d5c'),
    badge: 'Veg',
    rating: 4.7,
  },
  {
    id: 'croissant-loaf',
    name: 'Butter Milk Bread',
    description: 'Fluffy, golden milk bread — perfect for morning toast.',
    price: 75,
    category: 'Breads',
    image: img('photo-1509440159596-0249088772ff'),
    rating: 4.6,
  },
  {
    id: 'multigrain',
    name: 'Multigrain Loaf',
    description: 'Wholesome seeds & grains baked into a hearty loaf.',
    price: 110,
    category: 'Breads',
    image: img('photo-1598373182133-52452f7691ef'),
    badge: 'Veg',
    rating: 4.5,
  },

  // ---------------- Cakes ----------------
  {
    id: 'choco-truffle',
    name: 'Chocolate Truffle Cake',
    description: 'Rich Belgian chocolate sponge with silky ganache.',
    price: 550,
    category: 'Cakes',
    image: img('photo-1578985545062-69928b1d9587'),
    badge: 'Bestseller',
    rating: 4.9,
  },
  {
    id: 'red-velvet',
    name: 'Red Velvet Cake',
    description: 'Velvety cocoa layers with cream cheese frosting.',
    price: 600,
    category: 'Cakes',
    image: img('photo-1586788680434-30d324b2d46f'),
    badge: 'New',
    rating: 4.8,
  },
  {
    id: 'cheesecake',
    name: 'Blueberry Cheesecake',
    description: 'Creamy baked cheesecake topped with blueberry compote.',
    price: 480,
    category: 'Cakes',
    image: img('photo-1533134242443-d4fd215305ad'),
    rating: 4.7,
  },
  {
    id: 'cupcake',
    name: 'Vanilla Cupcakes (6)',
    description: 'Soft vanilla cupcakes swirled with buttercream.',
    price: 300,
    category: 'Cakes',
    image: img('photo-1614707267537-b85aaf00c4b7'),
    badge: 'Veg',
    rating: 4.6,
  },

  // ---------------- Pastries ----------------
  {
    id: 'croissant',
    name: 'Butter Croissant',
    description: 'Flaky, buttery layers baked to golden perfection.',
    price: 85,
    category: 'Pastries',
    image: img('photo-1555507036-ab1f4038808a'),
    badge: 'Bestseller',
    rating: 4.9,
  },
  {
    id: 'choco-pastry',
    name: 'Chocolate Pastry',
    description: 'Moist chocolate slice layered with ganache.',
    price: 95,
    category: 'Pastries',
    image: img('photo-1606313564200-e75d5e30476c'),
    rating: 4.7,
  },
  {
    id: 'danish',
    name: 'Fruit Danish',
    description: 'Buttery pastry with custard and glazed fruit.',
    price: 110,
    category: 'Pastries',
    image: img('photo-1608198093002-ad4e005484ec'),
    badge: 'New',
    rating: 4.6,
  },
  {
    id: 'donut',
    name: 'Glazed Donuts (4)',
    description: 'Pillowy donuts with a sweet sugar glaze.',
    price: 160,
    category: 'Pastries',
    image: img('photo-1551024601-bec78aea704b'),
    badge: 'Veg',
    rating: 4.8,
  },

  // ---------------- Burgers ----------------
  {
    id: 'classic-burger',
    name: 'Classic Chicken Burger',
    description: 'Crispy chicken patty, lettuce, cheese & house sauce.',
    price: 180,
    category: 'Burgers',
    image: img('photo-1568901346375-23c9450c58cd'),
    badge: 'Bestseller',
    rating: 4.8,
  },
  {
    id: 'veg-burger',
    name: 'Veggie Delight Burger',
    description: 'Golden veg patty with fresh crunch & tangy mayo.',
    price: 140,
    category: 'Burgers',
    image: img('photo-1520072959219-c595dc870360'),
    badge: 'Veg',
    rating: 4.6,
  },
  {
    id: 'double-cheese',
    name: 'Double Cheese Burger',
    description: 'Two juicy patties stacked with molten cheese.',
    price: 240,
    category: 'Burgers',
    image: img('photo-1550547660-d9450f859349'),
    badge: 'Spicy',
    rating: 4.9,
  },

  // ---------------- Pizza ----------------
  {
    id: 'margherita',
    name: 'Margherita Pizza',
    description: 'Classic tomato, basil & mozzarella on thin crust.',
    price: 260,
    category: 'Pizza',
    image: img('photo-1604382354936-07c5d9983bd3'),
    badge: 'Veg',
    rating: 4.7,
  },
  {
    id: 'pepperoni',
    name: 'Pepperoni Pizza',
    description: 'Loaded pepperoni with a gooey cheese blanket.',
    price: 340,
    category: 'Pizza',
    image: img('photo-1628840042765-356cda07504e'),
    badge: 'Bestseller',
    rating: 4.9,
  },
  {
    id: 'farmhouse',
    name: 'Farmhouse Pizza',
    description: 'Onion, capsicum, mushroom & sweet corn medley.',
    price: 320,
    category: 'Pizza',
    image: img('photo-1513104890138-7c749659a591'),
    badge: 'Veg',
    rating: 4.6,
  },

  // ---------------- Snacks ----------------
  {
    id: 'fries',
    name: 'Peri Peri Fries',
    description: 'Crispy fries tossed in fiery peri peri spice.',
    price: 120,
    category: 'Snacks',
    image: img('photo-1573080496219-bb080dd4f877'),
    badge: 'Spicy',
    rating: 4.7,
  },
  {
    id: 'nuggets',
    name: 'Chicken Nuggets (8)',
    description: 'Golden crunchy nuggets with dip.',
    price: 160,
    category: 'Snacks',
    image: img('photo-1562967914-608f82629710'),
    rating: 4.6,
  },
  {
    id: 'samosa',
    name: 'Punjabi Samosa (2)',
    description: 'Flaky pastry stuffed with spiced potato & peas.',
    price: 40,
    category: 'Snacks',
    image: img('photo-1601050690597-df0568f70950'),
    badge: 'Veg',
    rating: 4.8,
  },
  {
    id: 'sandwich',
    name: 'Grilled Veg Sandwich',
    description: 'Toasted sandwich packed with veggies & cheese.',
    price: 130,
    category: 'Snacks',
    image: img('photo-1528735602780-2552fd46c7af'),
    badge: 'Veg',
    rating: 4.5,
  },

  // ---------------- Beverages ----------------
  {
    id: 'cold-coffee',
    name: 'Cold Coffee',
    description: 'Thick, frothy cold coffee topped with cream.',
    price: 110,
    category: 'Beverages',
    image: img('photo-1461023058943-07fcbe16d735'),
    badge: 'Bestseller',
    rating: 4.8,
  },
  {
    id: 'cappuccino',
    name: 'Cappuccino',
    description: 'Espresso with steamed milk & silky foam art.',
    price: 90,
    category: 'Beverages',
    image: img('photo-1572442388796-11668a67e53d'),
    rating: 4.7,
  },
  {
    id: 'mango-shake',
    name: 'Mango Shake',
    description: 'Creamy shake blended with ripe Alphonso mango.',
    price: 120,
    category: 'Beverages',
    image: img('photo-1546173159-315724a31696'),
    badge: 'New',
    rating: 4.6,
  },
  {
    id: 'lemonade',
    name: 'Fresh Lime Soda',
    description: 'Zesty lime with a fizzy, refreshing kick.',
    price: 70,
    category: 'Beverages',
    image: img('photo-1621263764928-df1444c5e859'),
    badge: 'Veg',
    rating: 4.5,
  },
]
